services:
  wolbolt:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./cmd/wolbolt-cgi
        - action: rebuild
          path: ./pkg
        - action: rebuild
          path: ./go.mod
        - action: rebuild
          path: ./go.sum
        - action: rebuild
          path: ./docker/apache/wollet.conf
        - action: rebuild
          path: ./Dockerfile
    volumes:
      - ./public:/usr/local/apache2/htdocs/wollet
    ports:
      - 8080:80

  build-wolbolt-cgi:
    profiles:
      - build
    network_mode: bridge
    image: golang:1.23.7-bookworm
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - GOOS=${GOOS:-freebsd}
      - GOARCH=${GOARCH:-amd64}
    command:
      - go
      - build
      - -o
      - public/wolbolt.cgi
      - cmd/wolbolt-cgi/main.go

  build-wolnut:
    profiles:
      - build
    network_mode: bridge
    image: golang:1.23.7-bookworm
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - GOOS=${GOOS:-linux}
      - GOARCH=${GOARCH:-mipsle}
      - GOMIPS=${GOMIPS:-softfloat}
    command:
      - go
      - build
      - -ldflags=-s -w
      - -o
      - wolnut/wolnut
      - cmd/wolnut/main.go

  htpasswd:
    profiles:
      - tools
    network_mode: bridge
    image: httpd:2.4.63-bookworm
    working_dir: /workspace
    volumes:
      - .:/workspace
    entrypoint:
      - htpasswd
