name: Build and Release Binaries

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release Binaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build wolbolt-cgi binary for FreeBSD/amd64
        run: |
          GOOS=freebsd GOARCH=amd64 docker compose run --rm build-wolbolt-cgi

      - name: Build wolnut binary for MIPSLE with softfloat
        run: |
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat docker compose run --rm build-wolnut

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload wolbolt-cgi binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./public/wolbolt.cgi
          asset_name: wolbolt-cgi-freebsd-amd64
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload wolnut binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wolnut/wolnut
          asset_name: wolnut-linux-mipsle-softfloat
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  